# Generated by Django 3.1.1 on 2020-09-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
